const assert=require('assert/strict'),fs=require('fs'),path=require('path'),zlib=require('zlib'),crypto=require('crypto');
const {Router}=require('../router.js'),root=path.join(__dirname,'../data');
const p=JSON.parse(zlib.gunzipSync(fs.readFileSync(path.join(root,'moscow-core.json.gz'))));
const cat=JSON.parse(fs.readFileSync(path.join(root,'address-catalog.json'))),rows=[];
for(const s of cat.shards){const raw=fs.readFileSync(path.join(root,s.file));assert.equal(crypto.createHash('sha256').update(raw).digest('hex'),s.sha256);const chunk=JSON.parse(zlib.gunzipSync(raw));assert.equal(chunk.length,s.count);rows.push(...chunk);}
assert.equal(rows.length,20409);assert.equal(new Set(rows.map(a=>a[3])).size,rows.length);assert.equal(cat.count,rows.length);
const manifest=JSON.parse(fs.readFileSync(path.join(root,'manifest.json')));
for(const f of manifest.files)assert.ok(fs.statSync(path.join(root,f)).size<25*1024*1024);
for(const [street,files]of cat.streets)for(const f of files)assert.ok(JSON.parse(zlib.gunzipSync(fs.readFileSync(path.join(root,f)))).some(a=>a[0].slice(0,a[0].lastIndexOf(','))===street));
assert.equal(p.source.sha256,'e5dd91709a7a5786afb59b67ba52cecc829adc466a877bd610af5b4aeb1cf8cc');assert.equal(p.nodes.length,298548);assert.equal(p.edges.length,290312);
const mk=(nodes,edges,metro={stations:[],edges:[]})=>new Router({nodes,edges,streets:['test'],metro});
let r=mk([[0,0],[100,0]],[[0,1,100,2,0]]);assert.equal(r.walk([10,0],[90,0]).meters,80);assert.equal(r.walk([90,0],[10,0]),null);
r=mk([[0,0],[100,100],[0,100],[100,0]],[[0,1,141.4,0,0],[2,3,141.4,0,0]]);assert.equal(r.walk([0,0],[100,0]),null);
const s=(name,line,p)=>({name,line,p,colour:'#123456'}),metro={stations:[s('A','1',[0,0]),s('B','1',[1000,0]),s('C','2',[1000,1]),s('D','2',[2000,0])],edges:[{a:0,b:1,meters:1000,coords:[[0,0],[1000,0]]},{a:2,b:3,meters:1000,coords:[[1000,1],[2000,0]]}],transfers:[]};
r=mk([[0,0],[2000,0]],[[0,1,2000,0,0]],metro);assert.equal(r.metroPath(0,3,35,30),null);
metro.transfers=[{a:1,b:2,source:'relation/test'}];r=mk([[0,0],[2000,0]],[[0,1,2000,0,0]],metro);
const direct=r.metroPath(0,3,35,30,5,0),wait=r.metroPath(0,3,35,30,5,2);assert.equal(direct.transfers,1);assert.equal(wait.seconds-direct.seconds,120);assert.equal(r.metroPath(3,0,35,30),null);
const opts={mode:'metro',walkSpeed:4.8,metroSpeed:35,dwell:30,accessMinutes:3,transferMinutes:5,waitMinutes:0};
const begin=performance.now();r=new Router(p);const init=performance.now()-begin;
const a=r.stations.find(s=>s.name==='ВДНХ'&&s.line==='6'),b=r.stations.find(s=>s.name==='Парк Культуры'&&s.line==='5');
const start=performance.now(),route=r.route([{p:a.access},{p:b.access}],opts),leg=route.legs[0],time=performance.now()-start;
assert.equal(leg.mode,'metro');assert.ok(leg.transfers>=1);assert.ok(leg.lines.length>=2);
assert.ok(Math.abs(leg.seconds-(leg.walkSeconds+leg.rideSeconds+leg.transferSeconds+leg.accessSeconds+leg.waitSeconds))<.00001);
assert.ok(r.route([{p:a.access},{p:b.access}],{...opts,waitMinutes:2}).seconds>route.seconds);
const near=rows.find(a=>a[0]==='Тверская улица, 10'),nearby=rows.find(a=>a[0]==='улица Петровка, 18');assert.equal(r.mixed(near.slice(1,3),nearby.slice(1,3),opts).mode,'walk');
assert.throws(()=>r.route([{p:a.access},{p:b.access}],{...opts,walkSpeed:0}));
console.log('PASS',JSON.stringify({addresses:rows.length,shards:cat.shards.length,largestShardBytes:Math.max(...cat.shards.map(s=>s.bytes)),stations:r.stations.length,transferLinks:r.stations.reduce((n,s)=>n+s.outgoing.filter(e=>e.transfer).length,0)/2,initMs:Math.round(init),routeMs:Math.round(time),routeSeconds:Math.round(route.seconds),transfers:leg.transfers,lines:leg.lines}));
