const fs = require('fs'), path = require('path'), assert = require('assert/strict');
const {Router, Heap} = require('../router.js');
const mk = (nodes, edges) => new Router({nodes, edges, streets:['Тестовая улица'], metro:{stations:[],edges:[]}});
const h = new Heap(); [7,1,9,2,6,0,3,8,4,5].forEach(v=>h.push([v,v]));
assert.deepEqual(Array.from({length:10},()=>h.pop()[0]),[0,1,2,3,4,5,6,7,8,9]);
let r = mk([[0,0],[100,0]],[[0,1,100,0,0]]);
assert.equal(r.walk([10,0],[90,0]).meters,80); assert.equal(r.walk([90,0],[10,0]).meters,80);
assert.equal(r.walk([10,10],[10,10]).seconds,0);
assert.equal(r.walk([1000,1000],[10,0]),null);
r = mk([[0,0],[100,0]],[[0,1,100,2,0]]);
assert.equal(r.walk([10,0],[90,0]).meters,80); assert.equal(r.walk([90,0],[10,0]),null);
r = mk([[0,0],[100,100],[0,100],[100,0]],[[0,1,141.4,0,0],[2,3,141.4,0,0]]);
assert.equal(r.walk([0,0],[100,0]),null); // A drawn crossing is not a junction.
const p = JSON.parse(fs.readFileSync(path.join(__dirname, '../data/moscow-test.json')));
assert.equal(p.source.sha256,'e5dd91709a7a5786afb59b67ba52cecc829adc466a877bd610af5b4aeb1cf8cc');
assert.equal(p.addresses.length,20409);
assert.ok(p.nodes.every(n=>n.length===2&&n.every(Number.isFinite)));
assert.ok(p.edges.every(e=>e[0]>=0&&e[0]<p.nodes.length&&e[1]>=0&&e[1]<p.nodes.length&&e[2]>0&&e[3]>=0&&e[3]<=7));
const start=performance.now(); r=new Router(p); const init=performance.now()-start;
const names=['Тверская улица, 10','улица Петровка, 18','Тверская улица, 17'];
const stops=names.map(label=>({p:p.addresses.find(a=>a[0]===label).slice(1,3)}));
const t=performance.now(),route=r.route(stops,{mode:'walk',walkSpeed:4.8});const routeMs=performance.now()-t;
assert.ok(route.meters>1000&&route.meters<3000); assert.ok(route.seconds>1000&&route.seconds<2400);
assert.equal(route.seconds,route.legs.reduce((s,l)=>s+l.seconds,0));assert.equal(route.legs.length,2);
route.legs.forEach(l=>assert.ok(l.parts[0].coords.length>10));
const faster=r.route(stops,{mode:'walk',walkSpeed:6});assert.ok(Math.abs(faster.seconds/route.seconds-.8)<.00001);
const a=r.stations.find(s=>s.name==='ВДНХ'),b=r.stations.find(s=>s.name==='Сухаревская');
const mt=performance.now(),metro=r.mixed(a.p,b.p,{walkSpeed:4.8,metroSpeed:35,dwell:30,accessMinutes:3});const metroMs=performance.now()-mt;
assert.equal(metro.mode,'metro');assert.equal(metro.line,'6');assert.equal(metro.stations,4);
assert.ok(metro.parts.filter(p=>p.mode==='metro').every(p=>p.coords.length>=2&&p.meters>100));
assert.ok(metro.parts.filter(p=>p.mode==='metro').reduce((n,p)=>n+p.coords.length,0)>10);
const result={test:'real OSM + algorithm boundaries',initMilliseconds:Math.round(init),walkMilliseconds:Math.round(routeMs),metroMilliseconds:Math.round(metroMs),walkMeters:Math.round(route.meters),walkSeconds:Math.round(route.seconds),metroModelSeconds:Math.round(metro.seconds),packBytes:fs.statSync(path.join(__dirname, '../data/moscow-test.json')).size,addresses:p.addresses.length,nodes:p.nodes.length,edges:p.edges.length};
console.log('PASS', result);
